In [3]:
using DataFrames;
#Pkg.update("Combinatorics")
using Combinatorics

INFO: Precompiling module Polynomials.


In [5]:
data = readtable("testing.csv")

1799×45 DataFrames.DataFrame
│ Row  │ Month                 │ Text_General_Code                      │ x1   │
├──────┼───────────────────────┼────────────────────────────────────────┼──────┤
│ 1    │ "2006-01-01T00:00:00" │ "All Other Offenses"                   │ 4252 │
│ 2    │ "2006-01-01T00:00:00" │ "Arson"                                │ 44   │
│ 3    │ "2006-01-01T00:00:00" │ "DRIVING UNDER THE INFLUENCE"          │ 425  │
│ 4    │ "2006-01-01T00:00:00" │ "Disorderly Conduct"                   │ 381  │
│ 5    │ "2006-01-01T00:00:00" │ "Embezzlement"                         │ 40   │
│ 6    │ "2006-01-01T00:00:00" │ "Forgery and Counterfeiting"           │ 68   │
│ 7    │ "2006-01-01T00:00:00" │ "Fraud"                                │ 777  │
│ 8    │ "2006-01-01T00:00:00" │ "Gambling Violations"                  │ 9    │
│ 9    │ "2006-01-01T00:00:00" │ "Narcotic / Drug Law Violations"       │ 1195 │
│ 10   │ "2006-01-01T00:00:00" │ "Offenses Against Family and Children" │ 20   │
│ 11   │ "2006-01-01T00:00:00" │ "Other Assaults"                       │ 2160 │
⋮
│ 1788 │ "2011-12-01T00:00:00" │ "Rape"                                 │ 74   │
│ 1789 │ "2011-12-01T00:00:00" │ "Receiving Stolen Property"            │ 6    │
│ 1790 │ "2011-12-01T00:00:00" │ "Recovered Stolen Motor Vehicle"       │ 407  │
│ 1791 │ "2011-12-01T00:00:00" │ "Vagrancy/Loitering"                   │ 40   │
│ 1792 │ "2011-12-01T00:00:00" │ "Vandalism/Criminal Mischief"          │ 1398 │
│ 1793 │ "2011-12-01T00:00:00" │ "Weapon Violations"                    │ 171  │
│ 1794 │ "2011-12-01T00:00:00" │ "Thefts"                               │ 3780 │
│ 1795 │ "2011-12-01T00:00:00" │ "Burglary"                             │ 1048 │
│ 1796 │ "2011-12-01T00:00:00" │ "Robbery"                              │ 764  │
│ 1797 │ "2011-12-01T00:00:00" │ "Drinking Violation"                   │ 35   │
│ 1798 │ "2011-12-01T00:00:00" │ "Homicide"                             │ 26   │
│ 1799 │ "2011-12-01T00:00:00" │ "Aggravated Assault"                   │ 656  │

│ Row  │ Year │ Unemployment │ Child_mortality │ hospital_ambulization_rate │
├──────┼──────┼──────────────┼─────────────────┼────────────────────────────┤
│ 1    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 2    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 3    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 4    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 5    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 6    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 7    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 8    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 9    │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 10   │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
│ 11   │ 2006 │ 0.062        │ 87.5            │ 1608.9                     │
⋮
│ 1788 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1789 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1790 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1791 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1792 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1793 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1794 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1795 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1796 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1797 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1798 │ 2011 │ 0.107        │ 65.5            │ 1315.9                     │
│ 1799 │ 2011 │ 0.107        │ 65.5            │ 1315.9              

In [6]:
months = [ i for i in 1:12]
crimes = unique(data[2])

25-element DataArrays.DataArray{String,1}:
 "All Other Offenses"                     
 "Arson"                                  
 "DRIVING UNDER THE INFLUENCE"            
 "Disorderly Conduct"                     
 "Embezzlement"                           
 "Forgery and Counterfeiting"             
 "Fraud"                                  
 "Gambling Violations"                    
 "Narcotic / Drug Law Violations"         
 "Offenses Against Family and Children"   
 "Other Assaults"                         
 "Other Sex Offenses (Not Commercialized)"
 "Prostitution and Commercialized Vice"   
 "Rape"                                   
 "Receiving Stolen Property"              
 "Recovered Stolen Motor Vehicle"         
 "Vagrancy/Loitering"                     
 "Vandalism/Criminal Mischief"            
 "Weapon Violations"                      
 "Thefts"                                 
 "Burglary"                               
 "Robbery"                                
 "Drinking 

In [7]:
#create all possible combinations 
tuples = Array{Array{},1}()
for crime in crimes
    for month in months
        push!(tuples, [crime, month])
    end 
end

In [8]:
tuples #300 element

300-element Array{Array,1}:
 Any["All Other Offenses",1] 
 Any["All Other Offenses",2] 
 Any["All Other Offenses",3] 
 Any["All Other Offenses",4] 
 Any["All Other Offenses",5] 
 Any["All Other Offenses",6] 
 Any["All Other Offenses",7] 
 Any["All Other Offenses",8] 
 Any["All Other Offenses",9] 
 Any["All Other Offenses",10]
 Any["All Other Offenses",11]
 Any["All Other Offenses",12]
 Any["Arson",1]              
 ⋮                           
 Any["Aggravated Assault",1] 
 Any["Aggravated Assault",2] 
 Any["Aggravated Assault",3] 
 Any["Aggravated Assault",4] 
 Any["Aggravated Assault",5] 
 Any["Aggravated Assault",6] 
 Any["Aggravated Assault",7] 
 Any["Aggravated Assault",8] 
 Any["Aggravated Assault",9] 
 Any["Aggravated Assault",10]
 Any["Aggravated Assault",11]
 Any["Aggravated Assault",12]

In [9]:
test = []
averages = zeros(300,2)
#want to create an average for each month-type combination
for row in eachrow(data)
    #gets month 
    month = parse(split(row[:Month],"-")[2])
    #gets type
    crime = row[:Text_General_Code]
    #use find to get index with corresponding month and crime
    index = find(x -> x == [crime, month],tuples)[1]
    #keeps count of appearances
    averages[index,2] = averages[index,2] + 1
    averages[index,1] = averages[index,1] + row[:x1]
end 

In [10]:
averages

300×2 Array{Float64,2}:
 17288.0  6.0
 16323.0  6.0
 20456.0  6.0
 21892.0  6.0
 21127.0  6.0
 24172.0  6.0
 25587.0  6.0
 26719.0  6.0
 18014.0  6.0
 17037.0  6.0
 15552.0  6.0
 14912.0  6.0
   280.0  6.0
     ⋮       
  3977.0  6.0
  3457.0  6.0
  4545.0  6.0
  4829.0  6.0
  5242.0  6.0
  5181.0  6.0
  5388.0  6.0
  5031.0  6.0
  5038.0  6.0
  4698.0  6.0
  4049.0  6.0
  4071.0  6.0

In [11]:
avg = [averages[i,1]/averages[i,2] for i in 1:300]

300-element Array{Float64,1}:
 2881.33  
 2720.5   
 3409.33  
 3648.67  
 3521.17  
 4028.67  
 4264.5   
 4453.17  
 3002.33  
 2839.5   
 2592.0   
 2485.33  
   46.6667
    ⋮     
  662.833 
  576.167 
  757.5   
  804.833 
  873.667 
  863.5   
  898.0   
  838.5   
  839.667 
  783.0   
  674.833 
  678.5   

In [36]:
crime = [tuples[i,1][1] for i in 1:300]
month = [tuples[i,1][2] for i in 1:300]
dataframe = DataFrame(Month_Number = month, Text_General_Code = crime, Avg = avg)

300×3 DataFrames.DataFrame
│ Row │ Month_Number │ Text_General_Code    │ Avg     │
├─────┼──────────────┼──────────────────────┼─────────┤
│ 1   │ 1            │ "All Other Offenses" │ 2881.33 │
│ 2   │ 2            │ "All Other Offenses" │ 2720.5  │
│ 3   │ 3            │ "All Other Offenses" │ 3409.33 │
│ 4   │ 4            │ "All Other Offenses" │ 3648.67 │
│ 5   │ 5            │ "All Other Offenses" │ 3521.17 │
│ 6   │ 6            │ "All Other Offenses" │ 4028.67 │
│ 7   │ 7            │ "All Other Offenses" │ 4264.5  │
│ 8   │ 8            │ "All Other Offenses" │ 4453.17 │
│ 9   │ 9            │ "All Other Offenses" │ 3002.33 │
│ 10  │ 10           │ "All Other Offenses" │ 2839.5  │
│ 11  │ 11           │ "All Other Offenses" │ 2592.0  │
⋮
│ 289 │ 1            │ "Aggravated Assault" │ 662.833 │
│ 290 │ 2            │ "Aggravated Assault" │ 576.167 │
│ 291 │ 3            │ "Aggravated Assault" │ 757.5   │
│ 292 │ 4            │ "Aggravated Assault" │ 804.833 │
│ 293 │ 5            │ "Aggravated Assault" │ 873.667 │
│ 294 │ 6            │ "Aggravated Assault" │ 863.5   │
│ 295 │ 7            │ "Aggravated Assault" │ 898.0   │
│ 296 │ 8            │ "Aggravated Assault" │ 838.5   │
│ 297 │ 9            │ "Aggravated Assault" │ 839.667 │
│ 298 │ 10           │ "Aggravated Assault" │ 783.0   │
│ 299 │ 11           │ "Aggravated Assault" │ 674.833 │
│ 300 │ 12           │ "Aggravated Assault" │ 678.5   │

In [37]:
Month_Number = [parse(split(data[i,1],"-")[2])  for i in 1: length(data[1])]
new_data = DataFrame(Month = data[:Month],  Text_General_Code = data[:Text_General_Code], x1 = data[:x1], Month_Number =Month_Number )

1799×4 DataFrames.DataFrame
│ Row  │ Month                 │ Text_General_Code                      │ x1   │
├──────┼───────────────────────┼────────────────────────────────────────┼──────┤
│ 1    │ "2006-01-01T00:00:00" │ "All Other Offenses"                   │ 4252 │
│ 2    │ "2006-01-01T00:00:00" │ "Arson"                                │ 44   │
│ 3    │ "2006-01-01T00:00:00" │ "DRIVING UNDER THE INFLUENCE"          │ 425  │
│ 4    │ "2006-01-01T00:00:00" │ "Disorderly Conduct"                   │ 381  │
│ 5    │ "2006-01-01T00:00:00" │ "Embezzlement"                         │ 40   │
│ 6    │ "2006-01-01T00:00:00" │ "Forgery and Counterfeiting"           │ 68   │
│ 7    │ "2006-01-01T00:00:00" │ "Fraud"                                │ 777  │
│ 8    │ "2006-01-01T00:00:00" │ "Gambling Violations"                  │ 9    │
│ 9    │ "2006-01-01T00:00:00" │ "Narcotic / Drug Law Violations"       │ 1195 │
│ 10   │ "2006-01-01T00:00:00" │ "Offenses Against Family and Children" │ 20   │
│ 11   │ "2006-01-01T00:00:00" │ "Other Assaults"                       │ 2160 │
⋮
│ 1788 │ "2011-12-01T00:00:00" │ "Rape"                                 │ 74   │
│ 1789 │ "2011-12-01T00:00:00" │ "Receiving Stolen Property"            │ 6    │
│ 1790 │ "2011-12-01T00:00:00" │ "Recovered Stolen Motor Vehicle"       │ 407  │
│ 1791 │ "2011-12-01T00:00:00" │ "Vagrancy/Loitering"                   │ 40   │
│ 1792 │ "2011-12-01T00:00:00" │ "Vandalism/Criminal Mischief"          │ 1398 │
│ 1793 │ "2011-12-01T00:00:00" │ "Weapon Violations"                    │ 171  │
│ 1794 │ "2011-12-01T00:00:00" │ "Thefts"                               │ 3780 │
│ 1795 │ "2011-12-01T00:00:00" │ "Burglary"                             │ 1048 │
│ 1796 │ "2011-12-01T00:00:00" │ "Robbery"                              │ 764  │
│ 1797 │ "2011-12-01T00:00:00" │ "Drinking Violation"                   │ 35   │
│ 1798 │ "2011-12-01T00:00:00" │ "Homicide"                             │ 26   │
│ 1799 │ "2011-12-01T00:00:00" │ "Aggravated Assault"                   │ 656  │

│ Row  │ Month_Number │
├──────┼──────────────┤
│ 1    │ 1            │
│ 2    │ 1            │
│ 3    │ 1            │
│ 4    │ 1            │
│ 5    │ 1            │
│ 6    │ 1            │
│ 7    │ 1            │
│ 8    │ 1            │
│ 9    │ 1            │
│ 10   │ 1            │
│ 11   │ 1            │
⋮
│ 1788 │ 12           │
│ 1789 │ 12           │
│ 1790 │ 12           │
│ 1791 │ 12           │
│ 1792 │ 12           │
│ 1793 │ 12           │
│ 1794 │ 12           │
│ 1795 │ 12           │
│ 1796 │ 12           │
│ 1797 │ 12           │
│ 1798 │ 12           │
│ 1799 │ 12           │

In [38]:
joinedDataset = join(dataframe, new_data, on = [:Text_General_Code, :Month_Number])

1799×5 DataFrames.DataFrame
│ Row  │ Month_Number │ Text_General_Code             │ Avg     │
├──────┼──────────────┼───────────────────────────────┼─────────┤
│ 1    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 2    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 3    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 4    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 5    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 6    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 7    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 8    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 9    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 10   │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 11   │ 1            │ "All Other Offenses"          │ 2881.33 │
⋮
│ 1788 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1789 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1790 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1791 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1792 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1793 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1794 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1795 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1796 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1797 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1798 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1799 │ 12           │ "Weapon Violations"           │ 161.667 │

│ Row  │ Month                 │ x1   │
├──────┼───────────────────────┼──────┤
│ 1    │ "2006-01-01T00:00:00" │ 733  │
│ 2    │ "2007-01-01T00:00:00" │ 678  │
│ 3    │ "2008-01-01T00:00:00" │ 667  │
│ 4    │ "2009-01-01T00:00:00" │ 637  │
│ 5    │ "2010-01-01T00:00:00" │ 643  │
│ 6    │ "2011-01-01T00:00:00" │ 619  │
│ 7    │ "2006-01-01T00:00:00" │ 4252 │
│ 8    │ "2007-01-01T00:00:00" │ 3148 │
│ 9    │ "2008-01-01T00:00:00" │ 2891 │
│ 10   │ "2009-01-01T00:00:00" │ 2686 │
│ 11   │ "2010-01-01T00:00:00" │ 2488 │
⋮
│ 1788 │ "2006-12-01T00:00:00" │ 1874 │
│ 1789 │ "2007-12-01T00:00:00" │ 1743 │
│ 1790 │ "2008-12-01T00:00:00" │ 1483 │
│ 1791 │ "2009-12-01T00:00:00" │ 1269 │
│ 1792 │ "2010-12-01T00:00:00" │ 1210 │
│ 1793 │ "2011-12-01T00:00:00" │ 1398 │
│ 1794 │ "2006-12-01T00:00:00" │ 181  │
│ 1795 │ "2007-12-01T00:00:00" │ 162  │
│ 1796 │ "2008-12-01T00:00:00" │ 169  │
│ 1797 │ "2009-12-01T00:00:00" │ 153  │
│ 1798 │ "2010-12-01T00:00:00" │ 134  │
│ 1799 │ "2011-12-01T00:00:00" │ 171  │

In [39]:
joinedDataset[:deseasonalized] = map((x,y) -> x/y, joinedDataset[:x1], joinedDataset[:Avg])


1799-element Array{Float64,1}:
 1.10586 
 1.02288 
 1.00629 
 0.961026
 0.970078
 0.93387 
 1.47571 
 1.09255 
 1.00335 
 0.932207
 0.863489
 0.632693
 0.942857
 ⋮       
 1.25253 
 1.16498 
 0.9912  
 0.848168
 0.808733
 0.934388
 1.11959 
 1.00206 
 1.04536 
 0.946392
 0.828866
 1.05773 

In [47]:
delete!(joinedDataset,:x1)

1799×5 DataFrames.DataFrame
│ Row  │ Month_Number │ Text_General_Code             │ Avg     │
├──────┼──────────────┼───────────────────────────────┼─────────┤
│ 1    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 2    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 3    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 4    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 5    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 6    │ 1            │ "Aggravated Assault"          │ 662.833 │
│ 7    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 8    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 9    │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 10   │ 1            │ "All Other Offenses"          │ 2881.33 │
│ 11   │ 1            │ "All Other Offenses"          │ 2881.33 │
⋮
│ 1788 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1789 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1790 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1791 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1792 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1793 │ 12           │ "Vandalism/Criminal Mischief" │ 1496.17 │
│ 1794 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1795 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1796 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1797 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1798 │ 12           │ "Weapon Violations"           │ 161.667 │
│ 1799 │ 12           │ "Weapon Violations"           │ 161.667 │

│ Row  │ Month                 │ deseasonalized │
├──────┼───────────────────────┼────────────────┤
│ 1    │ "2006-01-01T00:00:00" │ 1.10586        │
│ 2    │ "2007-01-01T00:00:00" │ 1.02288        │
│ 3    │ "2008-01-01T00:00:00" │ 1.00629        │
│ 4    │ "2009-01-01T00:00:00" │ 0.961026       │
│ 5    │ "2010-01-01T00:00:00" │ 0.970078       │
│ 6    │ "2011-01-01T00:00:00" │ 0.93387        │
│ 7    │ "2006-01-01T00:00:00" │ 1.47571        │
│ 8    │ "2007-01-01T00:00:00" │ 1.09255        │
│ 9    │ "2008-01-01T00:00:00" │ 1.00335        │
│ 10   │ "2009-01-01T00:00:00" │ 0.932207       │
│ 11   │ "2010-01-01T00:00:00" │ 0.863489       │
⋮
│ 1788 │ "2006-12-01T00:00:00" │ 1.25253        │
│ 1789 │ "2007-12-01T00:00:00" │ 1.16498        │
│ 1790 │ "2008-12-01T00:00:00" │ 0.9912         │
│ 1791 │ "2009-12-01T00:00:00" │ 0.848168       │
│ 1792 │ "2010-12-01T00:00:00" │ 0.808733       │
│ 1793 │ "2011-12-01T00:00:00" │ 0.934388       │
│ 1794 │ "2006-12-01T00:00:00" │ 1.11959        │
│ 1795 │ "2007-12-01T00:00:00" │ 1.00206        │
│ 1796 │ "2008-12-01T00:00:00" │ 1.04536        │
│ 1797 │ "2009-12-01T00:00:00" │ 0.946392       │
│ 1798 │ "2010-12-01T00:00:00" │ 0.828866       │
│ 1799 │ "2011-12-01T00:00:00" │ 1.05773        │

In [49]:
joinedDataset = join(data, joinedDataset, on = [:Text_General_Code, :Month])

1799×48 DataFrames.DataFrame
│ Row  │ Month                 │ Text_General_Code                         │
├──────┼───────────────────────┼───────────────────────────────────────────┤
│ 1    │ "2006-01-01T00:00:00" │ "Aggravated Assault"                      │
│ 2    │ "2006-01-01T00:00:00" │ "All Other Offenses"                      │
│ 3    │ "2006-01-01T00:00:00" │ "Arson"                                   │
│ 4    │ "2006-01-01T00:00:00" │ "Burglary"                                │
│ 5    │ "2006-01-01T00:00:00" │ "DRIVING UNDER THE INFLUENCE"             │
│ 6    │ "2006-01-01T00:00:00" │ "Disorderly Conduct"                      │
│ 7    │ "2006-01-01T00:00:00" │ "Drinking Violation"                      │
│ 8    │ "2006-01-01T00:00:00" │ "Embezzlement"                            │
│ 9    │ "2006-01-01T00:00:00" │ "Forgery and Counterfeiting"              │
│ 10   │ "2006-01-01T00:00:00" │ "Fraud"                                   │
│ 11   │ "2006-01-01T00:00:00" │ "Gambling Violations"                     │
⋮
│ 1788 │ "2011-12-01T00:00:00" │ "Offenses Against Family and Children"    │
│ 1789 │ "2011-12-01T00:00:00" │ "Other Assaults"                          │
│ 1790 │ "2011-12-01T00:00:00" │ "Other Sex Offenses (Not Commercialized)" │
│ 1791 │ "2011-12-01T00:00:00" │ "Prostitution and Commercialized Vice"    │
│ 1792 │ "2011-12-01T00:00:00" │ "Rape"                                    │
│ 1793 │ "2011-12-01T00:00:00" │ "Receiving Stolen Property"               │
│ 1794 │ "2011-12-01T00:00:00" │ "Recovered Stolen Motor Vehicle"          │
│ 1795 │ "2011-12-01T00:00:00" │ "Robbery"                                 │
│ 1796 │ "2011-12-01T00:00:00" │ "Thefts"                                  │
│ 1797 │ "2011-12-01T00:00:00" │ "Vagrancy/Loitering"                      │
│ 1798 │ "2011-12-01T00:00:00" │ "Vandalism/Criminal Mischief"             │
│ 1799 │ "2011-12-01T00:00:00" │ "Weapon Violations"                       │

│ Row  │ x1   │ Year │ Unemployment │ Child_mortality │
├──────┼──────┼──────┼──────────────┼─────────────────┤
│ 1    │ 733  │ 2006 │ 0.062        │ 87.5            │
│ 2    │ 4252 │ 2006 │ 0.062        │ 87.5            │
│ 3    │ 44   │ 2006 │ 0.062        │ 87.5            │
│ 4    │ 906  │ 2006 │ 0.062        │ 87.5            │
│ 5    │ 425  │ 2006 │ 0.062        │ 87.5            │
│ 6    │ 381  │ 2006 │ 0.062        │ 87.5            │
│ 7    │ 63   │ 2006 │ 0.062        │ 87.5            │
│ 8    │ 40   │ 2006 │ 0.062        │ 87.5            │
│ 9    │ 68   │ 2006 │ 0.062        │ 87.5            │
│ 10   │ 777  │ 2006 │ 0.062        │ 87.5            │
│ 11   │ 9    │ 2006 │ 0.062        │ 87.5            │
⋮
│ 1788 │ 10   │ 2011 │ 0.107        │ 65.5            │
│ 1789 │ 1916 │ 2011 │ 0.107        │ 65.5            │
│ 1790 │ 143  │ 2011 │ 0.107        │ 65.5            │
│ 1791 │ 95   │ 2011 │ 0.107        │ 65.5            │
│ 1792 │ 74   │ 2011 │ 0.107        │ 65.5            │
│ 1793 │ 6    │ 2011 │ 0.107        │ 65.5            │
│ 1794 │ 407  │ 2011 │ 0.107        │ 65.5            │
│ 1795 │ 764  │ 2011 │ 0.107        │ 65.5            │
│ 1796 │ 3780 │ 2011 │ 0.107        │ 65.5            │
│ 1797 │ 40   │ 2011 │ 0.107        │ 65.5            │
│ 1798 │ 1398 │ 2011 │ 0.107        │ 65.5            │
│ 1799 │ 171  │ 2011 │ 0.107        │ 65.5            │

│ Row  │ hospital_ambulization_rate │ Cancer_mortality │ Days_good_air_quality │
├──────┼────────────────────────────┼──────────────────┼───────────────────────┤
│ 1    │ 1608.9                     │ 228.1            │ 154                   │
│ 2    │ 1608.9                     │ 228.1            │ 154                   │
│ 3    │ 1608.9                     │ 228.1            │ 154                   │
│ 4    │ 1608.9                     │ 228.1            │ 154                   │
│ 5    │ 1608.9                     │ 228.1            │ 154                   │
│ 6    │ 1608.9                     │ 228.1            │ 154             

In [50]:
writetable("deseasonalizedtraining.csv",joinedDataset)

In [35]:
parse(split("2006-01-01T00:00:00","-")[2])

1

In [56]:
a = [1,2,3,4,5,1,2]

7-element Array{Int64,1}:
 1
 2
 3
 4
 5
 1
 2

In [57]:
find(x -> x ==1,a) #rturns indices where condition is satisfied

2-element Array{Int64,1}:
 1
 6

In [58]:
a = [[1,2], [3,4], [5,6]]

3-element Array{Array{Int64,1},1}:
 [1,2]
 [3,4]
 [5,6]

In [59]:
find(x -> x == [3,4],a) 

1-element Array{Int64,1}:
 2